(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (cond ((not (eq? p password))
           (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else
            (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(begin
  (define acc (make-account 100 'secret-password))
  (assert (= ((acc 'secret-password 'withdraw) 40) 60))
  (assert (equal? ((acc 'some-other-password 'deposit) 50) "Incorrect password")))
