(define (make-account balance password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch p m)
    (cond ((not (eq? p password))
           (lambda (x) "Incorrect password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else
            (error "Unknown request: MAKE-ACCOUNT" m))))
  dispatch)

(define (make-joint acc pass new-pass)
  (lambda (p m)
    (if (eq? p new-pass)
      (acc pass m)
      (lambda (x) "Incorrect password"))))

(begin
  (define peter-acc (make-account 100 'open-sesame))
  (define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))
  (assert (= ((peter-acc 'open-sesame 'withdraw) 40) 60))
  (assert (equal? ((paul-acc 'open-sesame 'deposit) 20) "Incorrect password"))
  (assert (= ((paul-acc 'rosebud 'deposit) 20) 80)))
