(define (cube-root x)
        (define (improve-rate guess)
                (/ (- (improve guess) guess) guess))
        (define (good-enough? guess)
                (< (abs (improve-rate guess)) 0.0000001))
        (define (improve guess)
                (/ (+ (/ x (square guess)) (* 2 guess)) 3))
        (define (cube-root-iter guess)
                (if (good-enough? guess)
                    guess
                    (cube-root-iter (improve guess))))
        (cube-root-iter 1.0))
